name: Deploy code

on:
  push:
    branches:
      - develop
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v4
        with:
          tag_prefix: "v"
          major_pattern: "feat!"
          minor_pattern: "feat"
          format: "${major}.${minor}.${patch}"

      - name: Log version
        run: echo "Version is ${{ steps.version.outputs.version }}"

      - name: Set VERSION environment variable
        run: echo "VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV

      - name: Build and push Docker image using Kaniko
        uses: aevea/action-kaniko@master
        with:
          image: ${{ secrets.ROOM_SERVICE_NAME }}
          tag: ${{ env.VERSION }}
          path: ./src/
          build_file: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for room-images-server using Kaniko
        uses: aevea/action-kaniko@master
        with:
          image: ${{ secrets.ROOM_IMAGES_SERVER_NAME }}
          tag: ${{ env.VERSION }}
          path: ./nginx/
          build_file: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}