name: Deploy code

on:
  push:
    branches:
      - develop
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v4
        with:
          tag_prefix: "v"
          major_pattern: "feat!"
          minor_pattern: "feat"
          format: "${major}.${minor}.${patch}"

      - name: Log version
        run: echo "Version is ${{ steps.version.outputs.version }}"

      - name: Set VERSION environment variable
        run: echo "VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ROOM_SERVICE_NAME }}:${{ env.VERSION }} ./src

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ROOM_SERVICE_NAME }}:${{ env.VERSION }}